### ISSUE TITLE
ActivateCommand

### ISSUE THREAD

**Issue by Livijn** [wetcat-studios/fortie#37]
The `ActivateCommand` is not working. The code seems to be copied from something else, namely Matt Stauffers Joind.in 🤨

**Comment by agoransson** [comment]
Yes, that does look very strange. I can't really tell you why it looks like that, looking at the history it changed 2 years ago - from something very different. Obviously it's not even working in the current state.

Only thing I can think of is that I must've started some tutorial on laravels (then) new command structure and forgot about it before committing. I'll fix this.

**Comment by Livijn** [comment]
Yes, that commit probably sneaked its way in 😄
