### ISSUE TITLE
Required attributes issues in orders

### ISSUE THREAD

**Issue by bagendahl** [wetcat-studios/fortie#39]
I got "Required attributes are CustomerNumber, Description, OrderedQuantity" error when I try to add an order. Solution was to add OrderRows into writable and attribute and change required to: 
`protected $required_create = [
    'CustomerNumber',
    'OrderRows',
  ];

  protected $required_update = [
    'CustomerNumber',
  ];`

I do not now your code is a legacy from old api but solution above works. If you approve please add solution into your repo. 

Thanks

**Comment by agoransson** [comment]
Excellent, I'll have a look. Thanks.

**Comment by agoransson** [comment]
I recall some problems in this area when I first designed the library, it's really a problem in being multi-dimensional. The Order itself doesn't have a requirement for the Description I think, but according to the Fortnox API the Orderrow has that requirement*. I'll go with your fix, and perhaps review how to handle these checks in future.

Perhaps the best thing is just to allow attempts to create things without any check, only let Fortnox say when something is missing.

* Fortnox seems to allow a missing description anyway.

**Comment by bagendahl** [comment]
Hi, I think you forgot this fox because I had to add it by myself in latest version. Could you add this in core? 
Thanks
