### ISSUE TITLE
Review how parameters work.

### ISSUE THREAD

**Issue by agoransson** [wetcat-studios/fortie#44]
Right now parameters need to be bundled into the "filter" parameter, as we don't have specific "limit", "sortby" etc.

Need to rework how all search queries are handled.

**Comment by viktormaar** [comment]
This functionality was refactored later in #51.
Is there anything specific need to be added/fixed? Or this issue is closable?

**Comment by agoransson** [comment]
It's quite old, perhaps... let's close it!
