### ISSUE TITLE
STORT TACK

### ISSUE THREAD

**Issue by tanthammar** [wetcat-studios/fortie#57]
Vill bara säga stort tack för att du/ni skapat "fortie"!!!!
Har ni någon donation sida så bidrar jag gärna...

**Comment by tanthammar** [comment]
FYI, testar just nu på Laravel 7 och allt verkar funka bra...

**Comment by agoransson** [comment]
Super! =)

Donationer behöver jag inte - men hittar du några fel så får du gärna bidra med buggfix eller rapportering av fel.

**Comment by tanthammar** [comment]
Will do. Är du med i Slack Artisans Sverige?

**Comment by tanthammar** [comment]
Stänger eftersom det ju inte är en issue :)
