### ISSUE TITLE
Guzzle 7.0 and Fortie?

### ISSUE THREAD

**Issue by Darrrren** [wetcat-studios/fortie#67]
Has anyone looked at Guzzle 7.0 compatibility yet or is anybody using it with Fortie?  The stock `composer.json` has us on ^6.3.0 but the world is moving on quickly and Guzzle is a big part of that. 

The Guzzle Changelog suggests that 95% of users will be able to upgrade without problems as there's not so many breaking changes, take a look here:

[https://github.com/guzzle/guzzle/blob/7.0.1/CHANGELOG.md#700-beta1---2019-12-30](url)

Any thoughts anyone?

**Comment by agoransson** [comment]
Hi there.

I'm looking into making a more generic solution to the transportation of the requests (see #58). Guzzle will likely remain the default for a while longer, but it will be easier to replace it.

To answer your question... thanks. I didn't consider updating yet, but it should of course be updated.

**Comment by agoransson** [comment]
I will close this issue and let it remain linked to #58.

**Comment by Darrrren** [comment]
Ah that looks interesting. Yes with the recent release of Laravel 8 and Guzzle 7 being a prerequisite of that, I was curious if anybody had thought about it yet.  I'll keep my eyes peeled for updates on #58
