### ISSUE TITLE
Make the API version a setting.

### ISSUE THREAD

**Issue by agoransson** [wetcat-studios/fortie#70]
https://github.com/wetcat-studios/fortie/blob/54066690d760fd2b3e525ccdeab118d9726f7146/src/FortieRequest.php#L254

**Comment by viktormaar** [comment]
I didn´t even notice this yet. There is an `endpoint` setting in the config file for this, but never used 🙂

**Comment by viktormaar** [comment]
Fixed by https://github.com/wetcat-studios/fortie/commit/4c103d70bfda7bddafc9c9f4081af735981548a1 and https://github.com/wetcat-studios/fortie/commit/e7e28fe45789150dfad9c1e2a3f40549d1dfe79b
