### ISSUE TITLE
Wiki Error - Prices

### ISSUE THREAD

**Issue by Darrrren** [wetcat-studios/fortie#79]
In the Wiki, in Prices, the last line is written as:

`$price = $fortie->accounts()->update($priceList, $articleNumber, $fromQuantity, $params);`

This is wrong, it should be changed to: 

`$price = $fortie->prices()->update($priceList, $articleNumber, $fromQuantity, $params);`

The error provided by the Exception is:

>Argument 2 passed to Wetcat\Fortie\Providers\Accounts\Provider::update() must be of the type array, string given.

**Comment by Darrrren** [comment]
Ahh, I didn't realise I could edit the Wiki myself. I've corrected the error.

**Comment by agoransson** [comment]
Awesome! Thanks =)
