### ISSUE TITLE
Kan inte logga in, access-token eller client-secret saknas(2).

### ISSUE THREAD

**Issue by pajkho** [wetcat-studios/fortie#96]
Får följande felmeddelande trots att både access-token och client-secret är medskickat.

Kan inte logga in, access-token eller client-secret saknas(2).

**Comment by agoransson** [comment]
Ser ut som det ändrats - undrar när.

```
Accept: application/json
Authorization: Bearer {Access-Token}
Content-Type: application/json
```

Funderar på om vi borde plocka bort `Client-Secret` också från headers.

>The Client-Id, Client-Secret and Authorization-Code are only used during initial authorization of the connection between a customer’s account and your application.

**Comment by agoransson** [comment]
Relaterar lite till #58: borde ändra headers så de är anpassade efter vilken request man faktiskt gör mot Fortnox. Bör ju inte skicka med mer än onödigt, om än bara för att spara bandbredd... osäker på om det finns säkerhetshål att skicka med detta med alla requests.

**Comment by pajkho** [comment]
> Ser ut som det ändrats - undrar när.
> 
> ```
> Accept: application/json
> Authorization: Bearer {Access-Token}
> Content-Type: application/json
> ```
> 
> Funderar på om vi borde plocka bort `Client-Secret` också från headers.
> 
> > The Client-Id, Client-Secret and Authorization-Code are only used during initial authorization of the connection between a customer’s account and your application.

Låter rimligt att kunna plocka bort det. Jag vågade dock inte göra det ifall det fanns någon annan anledning till att det låg så.
